# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(default='1998-12-24', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='员工', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='第一次登录', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='17852417983', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='男', max_length=3),
        ),
    ]
