# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-05 11:07
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='内容')),
                ('abstract', models.CharField(blank=True, max_length=256, null=True, verbose_name='摘要')),
                ('article_cate', models.CharField(choices=[('code', '代码记录'), ('life', '生活感悟')], default='code', max_length=5, verbose_name='类别')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
