# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='article',
            name='article_cate',
            field=models.CharField(choices=[('代码', 'code'), ('生活感悟', '生活')], default='代码', max_length=5),
        ),
    ]
