# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180212_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_cate',
            field=models.CharField(choices=[('code', '代码记录'), ('life', '生活感悟')], default='code', max_length=5),
        ),
    ]
