# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 14:01
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180212_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_cate',
            field=models.CharField(choices=[('code', '代码记录'), ('life', '生活感悟')], default='code', max_length=5, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
    ]
